In [ ]:
import pandas as pd
import numpy as np


In [ ]:
data ={
    'Feature1':[10,20,30,40,50],
    'Feature2':[100,250,300,450,500]
}
df=pd.DataFrame(data)
print(df)

   Feature1  Feature2
0        10       100
1        20       250
2        30       300
3        40       450
4        50       500


In [ ]:
stdz=(df-df.mean())/df.std()
print(stdz)

   Feature1  Feature2
0 -1.264911 -1.370989
1 -0.632456 -0.436224
2  0.000000 -0.124635
3  0.632456  0.810130
4  1.264911  1.121719


In [ ]:
nmz=(df-df.min())/(df.max()-df.min())
print(nmz)

   Feature1  Feature2
0      0.00     0.000
1      0.25     0.375
2      0.50     0.500
3      0.75     0.875
4      1.00     1.000


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()
std_data = scaler.fit_transform(arr)
print(std_data)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
nm_data = scaler.fit_transform(arr)
print(nm_data)

[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
data=['low','medium','high','low','medium']
encoder = LabelEncoder()
encoded_data = encoder.fit_transform(data)
print(encoded_data)
df=pd.DataFrame({"Sizes":data})
df['En_Data']=encoded_data
print(df)

[1 2 0 1 2]
    Sizes  En_Data
0     low        1
1  medium        2
2    high        0
3     low        1
4  medium        2


In [ ]:
data=pd.DataFrame({'Category':['A','C','B','A']})
encoded_data=pd.get_dummies(data)
print(encoded_data)

   Category_A  Category_B  Category_C
0        True       False       False
1       False       False        True
2       False        True       False
3        True       False       False


In [ ]:
from category_encoders import OrdinalEncoder
data=pd.DataFrame({'size':['S','M','L','XL']})
encoder=OrdinalEncoder(mapping=[{'col':'size','mapping':{'S':1,'M':2},'L':3,'XL':4}])
encoded_data=encoder.fit_transform(data)
print(encoded_data)

   size
0   1.0
1   2.0
2  -1.0
3  -1.0


In [ ]:
!pip install category_encoders


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.9/81.9 kB 2.2 MB/s eta 0:00:00


In [ ]:

data=pd.DataFrame({'size':['S','M','L','XL']})
data.size.replace({'S':1,'M':2,'L':3,'XL':4},inplace=True)
print(data)

AttributeError: 'int' object has no attribute 'str'

In [ ]:
data=pd.DataFrame({'size':['S','M','L','XL']})
data.replace({'S':1,'M':2,'L':3,'XL':4},inplace=True)
print(data)

   size
0     1
1     2
2     3
3     4


In [ ]:
data

size
0     1
1     2
2     3
3     4